using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Carro
{
    class Program
    {
        static void Main(string[] args)
        {

            while (true)
            {
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                         _  _      ");
                Console.WriteLine("                                                                                        | || | _   ");
                Console.WriteLine("                                  __                                                    | || || |  ");
                Console.WriteLine("                           -    ~( @)   |                                               | || || |- ");
                Console.WriteLine("                         _________]_[__/_>________                                       -_  || |  ");
                Console.WriteLine("                     -- /  ____ | <>     |  ____  |                                         |  _/  ");
                Console.WriteLine("                      -=|_| __ |_|_______|_/ __ |__D                                       -| |    ");
                Console.WriteLine("___________________________(__)_____________(__)__________ _________________________________|_|- __");
                Thread.Sleep(300);
                Console.Clear();
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                            _  _                   ");
                Console.WriteLine("                                                                           | || | _                ");
                Console.WriteLine("                                  __                                       | || || |               ");
                Console.WriteLine("                         --    ~~( @)   |                                  | || || |-              ");
                Console.WriteLine("                         _________]_[__/_>________                          -_  || |               ");
                Console.WriteLine("                  --    /  ____ | <>     |  ____  |                            |  _/               ");
                Console.WriteLine("                     --=|_| __ |_|_______|_/ __ |__D                          -| |                 ");
                Console.WriteLine("___________________________(__)_____________(__)_______________________________|_|- _______________");
                Thread.Sleep(300);
                Console.Clear();
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                 _  _                              ");
                Console.WriteLine("                                                                | || | _                           ");
                Console.WriteLine("                                  __                            | || || |                          ");
                Console.WriteLine("                     ---       ~~( @)   |                       | || || |-                         ");
                Console.WriteLine("                    -    _________]_[__/_>________               -_  || |                          ");
                Console.WriteLine("                 ---    /  ____ | <>     |  ____  |                 |  _/                          ");
                Console.WriteLine("                   --  =|_| __ |_|_______|_/ __ |__D               -| |                            ");
                Console.WriteLine("__________________ ________(__)_____________(__)____________________|_|- _________________________ ");
                Thread.Sleep(300);
                Console.Clear();
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                      _  _                                         ");
                Console.WriteLine("                                                     | || | _                                      ");
                Console.WriteLine("                                  __                -| || || |                                     ");
                Console.WriteLine("                    ----      ~~~( @)   |            | || || |-                                    ");
                Console.WriteLine("                   --    _________]_[__/_>________    -_  || |                                     ");
                Console.WriteLine("                ---     /  ____ | <>     |  ____  |      |  _/                                     ");
                Console.WriteLine("                  --- -=|_| __ |_|_______|_/ __ |__D    -| |                                       ");
                Console.WriteLine("___________________________(__)_____________(__)____ ____|_|- _____________________________________");
                Thread.Sleep(300);
                Console.Clear();
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                _  _                                                               ");
                Console.WriteLine("                               | || | _                                                            ");
                Console.WriteLine("                              -| || || |      __                                                   ");
                Console.WriteLine("                   ---        ~~~( @)   |                                 ______              -    ");
                Console.WriteLine("                  --     _________]_[__/_>________                       |__  __|  --      _.----");
                Console.WriteLine("                ----    /  ____ | <>     |  ____  |                         ||       ---    /      ");
                Console.WriteLine("                 ---- -=|_| __ |_|_______|_/ __ |__D                        ||    --     __/ (  | (");
                Console.WriteLine("___________________________(__)_____________(__)____________________________||__________/__.-'|_|--");
                Thread.Sleep(300);
                Console.Clear();
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("     _  _                                                                                      _  _   ");
                Console.WriteLine("    | || | _                                                                                  | || |  ");
                Console.WriteLine("   -| || || |                     __                                                  __      | || |          ");  
                Console.WriteLine("    | || || |      ---   --  ~~~~( @)   |            ______                 ---      / _)     | || |          ");
                Console.WriteLine("     -_  || |     --  -- _________]_[__/_>________  |__  __|           --   _.----._/ /        -_  |          ");
                Console.WriteLine("        |  _/   ----  --/  ____ | <>     |  ____  |    ||          ---     /         /            |           ");
                Console.WriteLine("       -| |      ---- -=|_| __ |_|_______|_/ __ |__D   ||          -    __/ (  | (  |            -|           ");
                Console.WriteLine("___ ____|_|- ______________(__)_____________(__)_______||__________-___/__.-'|_|--|_|_____________|______");
                Thread.Sleep(300);
                Console.Clear();
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                                           ");
                Console.WriteLine("                                                                                        _  _               ");
                Console.WriteLine("                                                                                       | || | _            ");
                Console.WriteLine("                          __                                                  __      -| || || |          ");
                Console.WriteLine("                    -   ---  ~~~~( @)   |                           ---      / _)      | || || |          ");
                Console.WriteLine("                 --  -   _________]_[__/_>________             --   _.----._/ /         -_  || |          ");
                Console.WriteLine("                 -- --  /  ____ | <>     |  ____  |        ---     /         /             |  _/          ");
                Console.WriteLine("                    -  =|_| __ |_|_______|_/ __ |__D       -    __/ (  | (  |             -| |            ");
                Console.WriteLine("___________________________(__)_____________(__)___________-___/__.-'|_|--|_|_________ ____|_|- ___");
                Thread.Sleep(300);
                Console.Clear();
                Console.WriteLine("                                                                              __                                   ");
                Console.WriteLine("                                                                             / _)                                  ");
                Console.WriteLine("                                                                    _.----._/ /                                    ");
                Console.WriteLine("                                                                   /         /                                     ");
                Console.WriteLine("                                                                __/ (  | (  |                                      ");
                Console.WriteLine("                                                               /__.-'|_|--|_|                                      ");
                Console.WriteLine("                                                                      /    _  _       ");
                Console.WriteLine("                                                               /  /     / | || | _    ");
                Console.WriteLine("                           __                                 /     /    -| || || |  ");
                Console.WriteLine("             ______    --   - ~~~~( @)   |                                | || || |  ");
                Console.WriteLine("            |__  __|  --  _________]_[__/_>________                        -_  || |  ");
                Console.WriteLine("               ||      --/  ____ | <>     |  ____  |                          |  _/  ");
                Console.WriteLine("               ||   -   =|_| __ |_|_______|_/ __ |__D                        -| |    ");
                Console.WriteLine("_______________||___________(__)_____________(__)________________________ ____|_|- ________________");
                Thread.Sleep(300);
                Console.Clear();
                Console.WriteLine("                                                                                     __               ");
                Console.WriteLine("                                                                           --       / _)              ");
                Console.WriteLine("                                                                  ----     _.----._/ /                ");
                Console.WriteLine("                                                                     -    /         /                 ");
                Console.WriteLine("                                                                 --    __/ (  | (  |                  ");
                Console.WriteLine("                                                              -       /__.-'|_|--|_|                  ");
                Console.WriteLine("                                                                   _  _               ");
                Console.WriteLine("                                                                  | || | _            ");
                Console.WriteLine("                           __                                    -| || || |          ");
                Console.WriteLine(" ______                --   - ~~~~( @)   |                        | || || |          ");
                Console.WriteLine("|__  __|              --  _________]_[__/_>________                -_  || |          ");
                Console.WriteLine("   ||                  --/  ____ | <>     |  ____  |                  |  _/          ");
                Console.WriteLine("   ||             ---   =|_| __ |_|_______|_/ __ |__D                -| |            ");
                Console.WriteLine("___||_______________________(__)_____________(__)________________ ____|_|- _________________________");
                Thread.Sleep(300);
                Console.Clear();
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                       _  _                                             ");
                Console.WriteLine("                                                      | || | _       '  '                          ");
                Console.WriteLine("                          --                         -| || || |       '  ' '         __                      ");
                Console.WriteLine("                     --     - ~~~~( @)   |            | || || |        '  '  '      / _)                     ");
                Console.WriteLine("                    --  - _________]_[__/_>________    -_  || |            _.----._/ /                       ");
                Console.WriteLine("                     --  /  ____ | <>     |  ____  |      |  _/           /         /                        ");
                Console.WriteLine("                 --- -  =|_| __ |_|_______|_/ __ |__D    -| |          __/ (  | (  |                         ");
                Console.WriteLine("____________________________(__)_____________(__)____ ____|_|- _______/__.-'|_|--|_|________________");
                Thread.Sleep(300);
                Console.Clear();
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                 _  _                                                    ");
                Console.WriteLine("                                | || | _                                      ");
                Console.WriteLine("                                | || || |                            __                      ");
                Console.WriteLine("                   --     --  ~~~~( @)   |                    --    / _)                     ");
                Console.WriteLine("                   -- --  _________]_[__/_>________    --  _.----._/ /                       ");
                Console.WriteLine("                   --    /  ____ | <>     |  ____  |   -  /         /                        ");
                Console.WriteLine("                 --- -  =|_| __ |_|_______|_/ __ |__D  __/ (  | (  |                         ");
                Console.WriteLine("___________________----_____(__)_____________(__)____/__.-'|_|--|_|__________________________________");
                Thread.Sleep(300);
                Console.Clear();
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("       _  _                                                                              ");
                Console.WriteLine("      | || | _                                                       ");
                Console.WriteLine("      | || || |                                  __                      ");
                Console.WriteLine("      | || || |    -      --  ~~~~( @)   |      / _)                     ");
                Console.WriteLine("       -_  || |     --  - _________]_[__/_>____/_/_                       ");
                Console.WriteLine("          |  _/    -  -- /  ____ | <>     |  ____  |                      ");
                Console.WriteLine("         -| |     - - - =|_| __ |_|_______|_/ __ |__D                     ");
                Console.WriteLine("__________|_|- ____ -- _____(__)_____________(__)____________________________________________________");
                Thread.Sleep(300);
                Console.Clear();
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                        ");
                Console.WriteLine("                                                                                                                      ");
                Console.WriteLine("                                                                                               _  _       ");
                Console.WriteLine("                                                                                              | || |        ");
                Console.WriteLine("                __                                                                            | || ||       ");
                Console.WriteLine("         --    / _)  -- --  ~~~~( @)   |                                                      | || ||");
                Console.WriteLine("  --  _.----._/ /  -- - _________]_[__/_>________                                              -_  ||  ");
                Console.WriteLine("  -  /         /  --- /  ____ | <>     |  ____  |                                                 |  ");
                Console.WriteLine("  __/ (  | (  |  -- - =|_| __ |_|_______|_/ __ |__D                                              -| |");
                Console.WriteLine("/__.-'|_|--|_|_____- _____(__)_____________(__)___________________________________________________|_|");
                Thread.Sleep(300);
                Console.Clear();
            }

        }
    }
}
